sudo: required

language: node_js

node_js: 0.10

services:
  - mongodb
  - docker

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost
    - dev-controller

before_script:
  - npm install -g grunt-cli

script:
  - grunt coverage
